ALTER TABLE `user_notifications` MODIFY `type` ENUM(
  'PROFESSIONAL_APPLICATION_APPROVED',
  'PROFESSIONAL_APPLICATION_REJECTED',
  'PROFESSIONAL_IDENTITY_REVOKED',
  'PROFESSIONAL_IDENTITY_RESTORED',
  'SYSTEM'
) NOT NULL;
